language: node_js
node_js:
  - 7
  - 8

cache:
  directories:
    - "node_modules"

services:
  - mongodb

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info